/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskProveedoresRouteImport } from './routes/desk.proveedores'
import { Route as DeskPaymentsRouteImport } from './routes/desk.payments'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSociosRouteImport } from './routes/admin.socios'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminAuditUserIdRouteImport } from './routes/admin.audit.$userId'

const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskProveedoresRoute = DeskProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPaymentsRoute = DeskPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DeskRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSociosRoute = AdminSociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditUserIdRoute = AdminAuditUserIdRouteImport.update({
  id: '/audit/$userId',
  path: '/audit/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/socios': typeof AdminSociosRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/billing': typeof AppBillingRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/desk/proveedores': typeof DeskProveedoresRoute
  '/desk/': typeof DeskIndexRoute
  '/admin/audit/$userId': typeof AdminAuditUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/socios': typeof AdminSociosRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/billing': typeof AppBillingRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/desk/proveedores': typeof DeskProveedoresRoute
  '/desk': typeof DeskIndexRoute
  '/admin/audit/$userId': typeof AdminAuditUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/socios': typeof AdminSociosRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/billing': typeof AppBillingRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/desk/proveedores': typeof DeskProveedoresRoute
  '/desk/': typeof DeskIndexRoute
  '/admin/audit/$userId': typeof AdminAuditUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/desk'
    | '/login'
    | '/recuperar-password'
    | '/admin/pricing'
    | '/admin/socios'
    | '/admin/users'
    | '/app/billing'
    | '/app/checkout'
    | '/desk/payments'
    | '/desk/proveedores'
    | '/desk/'
    | '/admin/audit/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/recuperar-password'
    | '/admin/pricing'
    | '/admin/socios'
    | '/admin/users'
    | '/app/billing'
    | '/app/checkout'
    | '/desk/payments'
    | '/desk/proveedores'
    | '/desk'
    | '/admin/audit/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/desk'
    | '/login'
    | '/recuperar-password'
    | '/admin/pricing'
    | '/admin/socios'
    | '/admin/users'
    | '/app/billing'
    | '/app/checkout'
    | '/desk/payments'
    | '/desk/proveedores'
    | '/desk/'
    | '/admin/audit/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DeskRoute: typeof DeskRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/proveedores': {
      id: '/desk/proveedores'
      path: '/proveedores'
      fullPath: '/desk/proveedores'
      preLoaderRoute: typeof DeskProveedoresRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/payments': {
      id: '/desk/payments'
      path: '/payments'
      fullPath: '/desk/payments'
      preLoaderRoute: typeof DeskPaymentsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/socios': {
      id: '/admin/socios'
      path: '/socios'
      fullPath: '/admin/socios'
      preLoaderRoute: typeof AdminSociosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit/$userId': {
      id: '/admin/audit/$userId'
      path: '/audit/$userId'
      fullPath: '/admin/audit/$userId'
      preLoaderRoute: typeof AdminAuditUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPricingRoute: typeof AdminPricingRoute
  AdminSociosRoute: typeof AdminSociosRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminAuditUserIdRoute: typeof AdminAuditUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPricingRoute: AdminPricingRoute,
  AdminSociosRoute: AdminSociosRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminAuditUserIdRoute: AdminAuditUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCheckoutRoute: AppCheckoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DeskRouteChildren {
  DeskPaymentsRoute: typeof DeskPaymentsRoute
  DeskProveedoresRoute: typeof DeskProveedoresRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskPaymentsRoute: DeskPaymentsRoute,
  DeskProveedoresRoute: DeskProveedoresRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DeskRoute: DeskRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
